### ISSUE TITLE
Current live prices

### ISSUE THREAD

**Issue by stuarts0011** [yaleman/amberelectric#1]
Hi, any chance you could provide an example to pull only the current live price (integer) for:
(a) grid
(b) controlled load
(c) feed in tariff?

I would like to try to create a homeassistant sensor.

**Comment by stuarts0011** [comment]
> Hi, any chance you could provide an example to pull only the current live price (integer) for:
> (a) grid

pricelist = json.dumps(API.getpricelist(), indent=2)
liveprice = pricelist[23:25]
print ("The current price of power is %sc/KWH." % liveprice)

> (b) controlled load
?
> (c) feed in tariff?
?
> I would like to try to create a homeassistant sensor.

**Comment by yaleman** [comment]
I don't have much visibility into the data as it stands, but a more reliable way of getting the current price data is:

```
pricedata = API.getpricelist()
current_price = pricedata.get('currentPriceKWH')
print(f"Current price: {current_price}")
```

The website doesn't seem to provide the other data points, but the phone app might - if I could figure out a reliable way of capturing those communications I'd use it :)

**Comment by yaleman** [comment]
I *have* found another endpoint that might expose some of the data, will poke at it in the coming days...

**Comment by zylantha** [comment]
Any luck with progressing this?  

I'm embarking on a project to switch my Enphase to 'zero export' at times when there is negative feed in tariff, so having the current feed in rate from Amber is a critical step in this.

**Comment by yaleman** [comment]
No, sorry - work and life have gotten in the way - happy to help integrate anything people can find regarding API endpoints. Sadly they don't seem to provide documentation themselves :(

**Comment by yaleman** [comment]
I just found that I can email them for ad-hoc access, will see if they're interested...

**Comment by zylantha** [comment]
I think I found the same reference to them, and asked as well.

**Comment by zylantha** [comment]
I have their response and it looks like I can turn this into something, but it is completely different to the way that this original code was written.  The API takes a postcode and returns all of the raw data (both past, current and forecast), from which you can calculate the applicable rates - you don't need to authenticate at all.

Unfortunately it is returning the wrong network provider for my postcode (as there are two), but once I can get over that we should be able to rewrite the code to call this API and return the results pretty easily.  Ultimately I am aiming to turn this into a homebridge module with the end goal of me being able to (a) display the current import and export rates in the Home app on our phones, and (b) ask Siri on my homepod what the current price is, and have her tell me what it is (for both import and export).

**Comment by zylantha** [comment]
I have a solution for the network provider issue, and have written a basic script to pull and display the current price, however the feedin tariff isn't exactly the same as what's displayed in the app (it's a cent off).  I will have to monitor it tomorrow and try to figure out what's going on.

This will likely be a new repo as it's a complete rewrite, but thought I'd give you a heads up on my progress so far.

Example output of the new code:
Network:          Jemena
Period:           2020-09-15T00:00:00
Usage Tariff:     15.9 c/kWh
Feedin Tariff:    6.0 c/kWh

**Comment by zylantha** [comment]
My code is now working and in my fork.  It's quick and dirty but does the job.

https://github.com/zylantha/amberelectric

(see amber.py)

**Comment by yaleman** [comment]
I'm happy to merge the code together to extend the existing module, if there's auth and non-auth endpoints there's no reason they can't live together 👍🏻

**Comment by yaleman** [comment]
Amber's taken over this project, closing - might want to raise any future issues with them and their new API.
